### PR TITLE
new AddOn EditableVariableEditor 

### PR DESCRIPTION
**Pull request by yfcc**
This simple app is to provide a tool for editing  editable variables in an existing configuration file. With this addon, one can 
1. move group of variables around, 
2. duplicate and 
3. insert new variables at specified location.

### CODE REVIEW

**Comment by joschaschmiedt** [comment]
Hey, this looks very useful. I'll try to have a closer look next week.

On which MATLAB version did you develop it?

**Comment by yfcc** [comment]
> Hey, this looks very useful. I'll try to have a closer look next week.
> 
> On which MATLAB version did you develop it?

`EditableVariableEditor.mlapp` was developed with MATLAB R2018b App Designer. Class definition (`EditableVariableEditor.m`) was then copyed from the code view in App Designer. 

It was tested with MATLAB 2020a on the cluster, App Designer in MATLAB 2010a  will generate a slighter different class definition. The old class definition sript generated from 2018b, if launched directly, works as well in MATLAB 2020a.

**Comment by joschaschmiedt** [comment]
Hey @yfcc ,
 Did you on purpose close this pull request?

**Comment by yfcc** [comment]
no...it was a mistake... i will create a new pull request

**Pull request closed without merging**
